; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 74880
lib_deps = 
	knolleary/PubSubClient@^2.8
	https://github.com/SunshadeCorp/TFT_eSPI_easybms_slave/archive/80581bad7ac4bc57272209fe9ffe2d54dcc8fdb1.zip ; Configured version of a c6 port
	; bodmer/TFT_eSPI@^2.5.43
	https://github.com/mkrasselt1/ve.bus-library.git
	eyr1n/ESP32_TWAI@^0.0.5
extra_scripts = 
	pre:platformio_version_increment/version_increment_pre.py
check_tool = cppcheck, clangtidy

; [env:esp32-c6-devkitc-1]
; platform = espressif32
; board = esp32-c6-devkitc-1

[env:esp32-c6-devkitm-1]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
; platform = espressif32
board = esp32-c6-devkitm-1
; build_unflags =
; 	-std=gnu++2b
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CORE_DEBUG_LEVEL=5

[env:esp32-c6-easybms]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitm-1
; build_unflags =
; 	-std=gnu++2b
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CORE_DEBUG_LEVEL=5
	-D LED_STATUS=15
	-D LED_DATA_RGB=14

; [env:lolin_c3_mini]
; platform = espressif32
; board = lolin_c3_mini

; [env:lolin_s2_mini]
; platform = espressif32
; board = lolin_s2_mini
